name: Deploy

on:
  push:
    branches:
      - main
  # workflow_dispatch:

jobs:


  build-and-deploy-staging:
    runs-on: ubuntu-latest
    # needs: manual-approval
    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}            
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  
      FRONTEND_DEPLOY_PATH: /app/khatibalami     
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }} 
      SERVER_USER: ${{secrets.SERVER_USER}}
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
      
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  
      
     
      - name: Install dependencies and build frontend
        run: |
          cd Frontend/
          npm install --legacy-peer-deps
          npm run build --parallel

     
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      # - name: Check if SSH key is added
      #   run: ssh-add -l    
      # - name: Test SSH Connection
      #   run: ssh -o StrictHostKeyChecking=no -v -p 16446 vagrant@0.tcp.in.ngrok.io 'echo "SSH Connected"'
     
      - name: Deploy React frontend to the server
        run: |
          # Copy the built dist folder to the server
          scp -v  -o StrictHostKeyChecking=no -P 11997 -r dist/* ${{env.SERVER_USER}}@${{env.SERVER_IP}}:${{ env.FRONTEND_DEPLOY_PATH }}
           ssh -v -o StrictHostKeyChecking=no -p 11997 ${{env.SERVER_USER}}@${{env.SERVER_IP}} 'sudo systemctl restart nginx'
           
            
  # manual-approval:
  #   runs-on: ubuntu-latest
  #   needs: build-and-deploy-staging
  #   if: github.event_name == 'workflow_dispatch' 
  #   steps:
  #     - name: Wait for manual approval
  #       run: echo "Waiting for manual approval..."
